- CHANGELOG.md
- package.json
- src/extension.ts
- src/run.ts
But also try not to change ports unnecessarily (each workspace tries to reuse the previous random port, if available)
> Launch Shiny apps on random port by default

- .github/workflows/publish.yml
This PR adds a GHA workflow step to publish the extension to Open-VSX.org (in addition to the existing VS Code Marketplace publishing step).
> First attempt at Open VSX publish (dry run)

- CHANGELOG.md
- src/extension-api-utils/getRemoteSafeUrl.ts
- src/extension-api-utils/runShellCommand.ts
- src/run.ts
Since Workbench runs the Python process on the server, a special URL is required to access the localhost port. This takes code from https://github.com/rstudio/shinyuieditor for forming the special URL.
> Posit Workbench compatibility

- CHANGELOG.md
- package.json
- src/extension.ts
- src/run.ts
Anytime you see "Run Shiny App" on the editor run menu, you should now also see "Debug Shiny App" right below it. This will launch the Python debugger on the currently focused Shiny app file, using a random-ish port, and launch the Simple Browser when the app is ready.
- There's an advanced debugger config flag `justMyCode` which I've hardcoded to `true`--this means that breakpoints in third party packages won't be respected. LMK if you disagree.
(I have done these all BTW, just documenting the scenarios I thought worth testing)
- Set breakpoints in various places (top level, in server function, in `@reactive.XXX` and render functions) in app.py and Shiny modules and ensure the debugger actually stops on them.
- Invoking "Debug Shiny App", and then invoking it again without stopping the …
> Add "Debug Shiny App" command to editor run menu

- CHANGELOG.md
- package.json
- src/constants.ts
- src/extension.ts
- src/retry-utils.ts
- src/run.ts
- src/shell-utils.ts
- src/test/suite/index.ts
- yarn.lock
Fixes #16
Fixes #23
When using the "Run Shiny App" command, the Python executable path and the app file path are both potentially in need of escaping, due to spaces or special characters. Today, we don't do that, so if you installed Python on Windows with "Install for all users", putting Python under C:\Program Files, we fail to launch every time if you try to use the system Python (as opposed to a venv, then it would depend if the venv path has any spaces in it).
However, the _way_ that escaping needs to be performed differs based on what type of shell VS Code's integrated terminal is configured to launch. On my Windows installation, for example, I get the following choices:
* PowerShell
* Git Bash
* Command Prompt (cmd.exe)
* Ubuntu (WSL)
* JavaScript Debug Terminal
* R Terminal
Since …
> Handle spaces and special characters in Python exec path and app file

- CHANGELOG.md
- package.json
- src/constants.ts
- src/extension.ts
- src/net-utils.ts
- src/port-settings.ts
- src/retry-utils.ts
- src/run.ts
- src/shell-utils.ts
Really surprisingly difficult to get it working semi-reliably with Codespaces' port forwarding. Also requires https://github.com/posit-dev/py-shiny/pull/1167.
I ended up moving a lot of code around, as run.ts was getting too unwieldy for me to make sense of, much less someone else reviewing it. So the diff doesn't make much sense--I'd just review the new run.ts from the top down.
> Codespaces compatibility

- .github/workflows/publish.yml
Adds a step to upload the packaged `.vsix` file to the GitHub action run as an artifact, which makes it easier to download and test the extension.
We could also consider uploading the extension as a release artifact ([an example workflow is outlined here](https://cezarypiatek.github.io/post/develop-vsextension-with-github-actions/#release-workflow)).
> ci: Upload the `.vsix` package to GitHub actions as artifact

- .github/workflows/publish.yml
- package.json
In PRs from my personal fork, the publish steps attempt to run but fail due to the missing `pat`. This PR adds `yarn vsix` (which is helpful locally) and builds and uploads the vsix artifact independent of the publish steps.
I also prevented the publishing steps from running for forks outside the `posit-dev` org.
> ci: always build and upload the vsix artifact

- README.md
* Fixes #33
* Fixes #43
* Describes Shiny for R features, keeping Python features in the foreground
* Updates several `shiny.rstudio.com` links to `shiny.posit.co` counterparts.
> Update README to include Shiny for R apps and options

- src/extension.ts
- src/run.ts
Fixes #38
Detects Shiny apps from files name `ui.R`, `server.R`, `global.R` and passes the directory containing the file to `shiny::runApp()` instead of the file path.
Note that we still require the word "shiny" to appear in the file contents in these cases, so sometimes `server.R` or `global.R` might not activate the extension. Users can still manually activate the "Run Shiny app" command in these cases.
> Improve support for Shiny for R apps that use `ui.R` and friends

- CHANGELOG.md
- package.json
- src/extension-api-utils/extensionHostPreview.ts
- src/net-utils.ts
Adds a new setting allowing users to choose whether the app should be opened internally, externally, or if no preview should be opened at all.
> feat: Add `shiny.previewType` configuration setting

- CHANGELOG.md
- snippets/shiny.json
Adds a snippet for `shinyexpress` using the default example on https://shinylive.io/py/editor
```py
from shiny.express import input, render, ui
ui.input_slider("n", "N", 0, 100, 20)
@render.text
def txt():
return f"n*2 is {input.n() * 2}"
```
> feat(snippets): Add a Shiny Express app snippet

- .github/workflows/publish.yml
Uses `actions/checkout@v4`, `actions/setup-node@v4` and `actions/upload-artifact@v4` to avoid warnings about deprecated node versions.
> ci: Bump to latest v4 actions

- src/net-utils.ts
We pre-load `about:blank` internally to clear the internal browser or signal that we're working on opening the Shiny app, but for external previews this step is unnecessary.
> fix: Don't open blank page in external browser

- CHANGELOG.md
- README.md
- package.json
- src/extension.ts
- src/shinylive.ts
- yarn.lock
This PR adds support for creating and saving Shinylive apps to the vscode extension with three commands:
1. **Create ShinyLive Link from Active File**. Sends the currently open single-file app to Shinylive, e.g. good for simple, single-file `app.py` or `app.R` examples.
2. **Create Shinylive Link from Selected Files**. In the file explorer tree, when right clicking on a file, a directory or a selection of multiple files/directories, users can select this command to send the selection to Shinylive.
3. **Save App from Shinylive Link**. Paste a [shinylive.io](https://shinylive.io) link and choose a directory or path where the app in the link should be saved. 
* If the Shinylive link points to a **single-file app**, users can pick a file location for the app, which may also overwrite an …
> feat: Support Shinylive export/import

- CHANGELOG.md
- src/shell-utils.ts
Fixes #46 
Prior to this PR, for `cmd.exe` commands, we would escape special characters and then, if the escaped string contains a space we'd wrap the string in `" "`.
For a string like `C:\Program Files (x86)\R\R-4.3.3\bin\Rscript.exe`, we'd turn `(` and `)` into `^(` and `^)`, but we'd then also wrap the string in `""` resulting in 
```
"C:\Program Files ^(x86^)\R\R-4.3.3\bin\Rscript.exe"
```
This would break because the `""` handles the escaping of the parenthesis. This PR changes the escaping to either escape individual special characters or wrap the string in `""` if it contains a space.
> Fix escaping for `cmd.exe`: either quote or escape individual special characters

- package.json
- src/extension.ts
- src/run.ts
- src/shinylive.ts
Updates the extension ID to be `Posit.shiny` and moves the extension to `v1.0.0`.
The outdated extension points to this extension as a dependency and uninstalls itself upon activation.
For #53
> Rename extension - Part 1 - New name

- .github/workflows/publish.yml
High priority follow up from #53, this finishes up the work in https://github.com/posit-dev/shiny-vscode/commit/c348df2b68dce61dffd3dd75adc232a653363460
* We now only run the publish jobs when we're actually wanting to publish the extension, i.e. on tags pushed to the `posit-dev` owned repo. **Note: this fixes a bug I introduced when working quickly to get the marketplace extension published.**
* Otherwise we lint and build the extension, where building the extension also calls `yarn compile`. This is a superset of what happens when `dryRun: true`, so the extra dry run publishing isn't required.
* The publish jobs fail silently if the extension is already published by setting `skipDuplicate: true` in the `publish-vscode-extension` settings.
All jobs are fast enough that it's not worth the …
> ci: clean up publish actions

- CHANGELOG.md
- package.json
- src/extension-onUri.ts
- src/extension.ts
- src/run.ts
- src/shinylive.ts
Closes #58
Adds support for `positron://`, `vscode://`, `vscode-insiders://`, or `cursor://` links of the form
```
vscode://posit.shiny/shinylive?url={encodeURIComponent(shinylive_url)}
```
Clicking a link like this will open Positron/VS Code/Cursor and prompt the user to choose a location to save the file, building on the existing "Save App from Shinylive Link" command.
https://github.com/user-attachments/assets/8fda83a9-4bf5-4a2d-a1ee-5ca23b0ea1fe
These URLs are easy to construct:
```js
const shinyliveUrl = "https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4mQiABM4dZfI4AdCPp0Y2AJgAUusAAk4AG1vFlAdym21AQksBKQxwxcFMgB9FlsODToLSEtlSwA5GKYABmUARiSUphMknwM8gAFVCIwSDX0NGiYyPjIzL0R9JiaVODJ5OggmGksIACoTMVEQAMUMCDqmXqyAX0t9M …
```
> feat: Support opening shinylive apps locally from a `vscode://` or `positron://` URL

- CHANGELOG.md
- src/run.ts
Currently, pressing the "play" button to run an open app will run the app using the file as it is on disk, ignoring any changes in the current editor.
This PR updates the "Run Shiny app" command to save the currently active file if it's dirty, which matches the behavior of the Quarto `.qmd` preview button as well as the "Run Shiny app" experience in RStudio.
If we're worried about this being too presumptive, we could put this behind a configuration setting. But note that this behavior isn't optional in the Quarto extension.
> feat: Save active editor before running the app

- src/extension-onUri.ts
Removes the extra cancel button when saving a shinylive app from a VS Code URI.
> fix: remove extra cancel option in shinylive URI handler

- src/shinylive.ts
This PR should not introduce any behavior changes.
As pointed out in https://github.com/posit-dev/shiny-vscode/pull/70#discussion_r1729368212, `askUserForOutputLocation()` blends the single-file app and multi-file app cases. While they follow a similar flow, there are checks that are important in one or the other case that are interleaved.
This PR separates these into two functions: `askUserForOutputFile()` and `askUserForOutputDirectory()`.
This makes it much easier to differentiate in `shinyliveSaveAppFromUrl()` how the single-file app workflow differs from the multi-file app workflow.
> refactor: `shinyliveSaveAppFromUrl()`

- src/net-utils.ts
I initially had a 10s wait before the "would you like to continue" appears, but in https://github.com/posit-dev/shiny-vscode/pull/65#discussion_r1686848560 we bumped this to 20s.
I had forgotten that these 10s are balancing both slow-opening apps as well as apps that fail immediately. Because we're using `terminal.sendText()`, we don't have any insight into what has happened in the Terminal. When an app fails immediately (say `shiny` isn't installed), we still have to wait for the 10s timeout before we show the "something's not right dialog".
To mitigate this, if the user clicks "keep waiting", we'll bump up the wait time to 30s.
> Wait 10s instead of 20s before asking user

- src/net-utils.ts
Updates the text of the message when we fail to connect to the Shiny app to say
> Shiny app took longer than 10s to start so we have not opened the preview.
where we previously said
> Shiny app took longer than 10s to start, not opening the browser.
which makes it sounds like Shiny didn't open the browser rather than "we're not going to open the preview".
Also while here I realized we could use progress bar incrementing to give a sense of how long we'll wait before giving up.
https://github.com/user-attachments/assets/63bbd15d-d2f6-4b62-a34f-d665cece3c9c
cc @karangattu 
btw, @jcheng5 the example above shows why I changed the default wait back to 10s in #74. Notice that the Shiny app never starts in the clip. We can't detect this automatically, we have to wait for the app launch to …
> Improve messaging of "took too long" message

- src/net-utils.ts
- src/retry-utils.ts
- src/run.ts
When I press the Play/Run button when the Shiny app is already running, I see this error:
This happens because the extension tries to execute `shiny run` before the ports have been released by the system.
This PR makes it wait until the ports are released before it tries to start the app again.
> Wait until server port is available before starting app
